routes:
  - body_re: ".*development.*"
    url: "https://hooks.slack.com/services/DDDDDDDD"

  - body_re: ".*testing.*"
    url: "https://hooks.slack.com/services/TTTTTTTT"

  - body_re: ".*staging.*"
    url: "https://hooks.slack.com/services/SSSSSSSS"
